# Generated by Django 3.2.7 on 2021-10-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='None'),
        ),
    ]
