# Generated by Django 3.2.7 on 2021-10-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20211004_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlist',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='itemlist',
            old_name='list_id',
            new_name='list_name',
        ),
    ]
