# Generated by Django 3.2.7 on 2021-10-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20211004_1438'),
        ('items', '0003_auto_20211004_1641'),
    ]

    operations = [
    ]
