# Generated by Django 3.2.7 on 2021-10-05 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0004_merge_0003_auto_20211004_1438_0003_auto_20211004_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlist',
            old_name='item_id',
            new_name='user_list',
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='list_id',
        ),
        migrations.AddField(
            model_name='itemlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default='None'),
        ),
    ]
