# Generated by Django 3.2.7 on 2021-10-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20211005_1022'),
        ('items', '0004_merge_0003_auto_20211004_1438_0003_auto_20211004_1641'),
    ]

    operations = [
    ]
