# Generated by Django 3.2.7 on 2021-10-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_merge_20211005_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlist',
            old_name='item',
            new_name='items',
        ),
    ]
