# Generated by Django 3.2.7 on 2021-10-06 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20211005_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='list_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='user_list',
        ),
        migrations.AddField(
            model_name='itemlist',
            name='user_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.item'),
        ),
    ]
