# Generated by Django 3.2.7 on 2021-10-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20211006_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='list_name',
            field=models.CharField(default='New List', max_length=100),
        ),
    ]
