# Generated by Django 3.2.7 on 2021-10-08 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_itemlist_list_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='user_list',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='itemList',
        ),
    ]
