# Generated by Django 3.2.7 on 2021-10-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlist',
            old_name='list_id',
            new_name='list_name',
        ),
        migrations.RenameField(
            model_name='userlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
